version: '3'

services:
  app:
    image: rrim/kaddem-app:1.0
    ports:
      - "8089:8089"  # Expose the application on port 8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db
    networks:
      - monitoring

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: kaddem
    volumes:
      - db_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"  # Prometheus accessible on port 9090
    networks:
      - monitoring
    command: |
      --config.file=/etc/prometheus/prometheus.yml
    entrypoint: >
      sh -c 'echo "
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: \'spring-boot-backend\'
          metrics_path: \'/actuator/prometheus\'
          static_configs:
            - targets: [\'app:8089\']
      " > /etc/prometheus/prometheus.yml && /bin/prometheus --config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Grafana accessible on port 3000
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  db_data:
