pipeline {
    agent any

    stages {
        stage('Checkout GIT') {
            steps {
                echo 'Pulling ...'
                git(
                    branch: 'RimOuertani-5SAE7-G5',
                    url: 'https://github.com/SghaierAya1/5SAE7-G5-Kaddem.git'
                )
            }
        }

        stage('MVN CLEAN') {
            steps {
                echo "Running Maven Clean..."
                sh 'mvn clean' // Utilisez le wrapper Maven si disponible
            }
        }

        stage('MVN COMPILE') {
            steps {
                echo "Running Maven Compile..."
                sh 'mvn compile' // Utilisez le wrapper Maven si disponible
            }
        }

        stage('Static Analysis') {
            steps {
                sh 'mvn sonar:sonar -Dsonar.login=admin -Dsonar.password=Rim12356113*'
            }
        }
    }
}
