pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from SCM
                checkout scm
            }
        }

        stage('MVN CLEAN') {
            steps {
                echo "Running Maven Clean..."
                sh './mvnw clean' // Utilisez le wrapper Maven si disponible
            }
        }

        stage('MVN COMPILE') {
            steps {
                echo "Running Maven Compile..."
                sh './mvnw compile' // Utilisez le wrapper Maven si disponible
            }
        }

        stage('Static Analysis') {
            steps {
                sh 'mvn sonar:sonar -Dsonar.login=admin -Dsonar.password=Rim12356113* -Dmaven.test.skip=true'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
