pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from SCM
                checkout scm
            }
        }

       stage('Build') {
                   steps {
                       script {
                           echo "Building the project with Maven..."
                           dir('kaddem') {  // Navigate to the kaddem directory
                               sh 'mvn clean install'  // Build the project
                           }
                       }
                   }

        stage('SonarQube Analysis') {
            steps {
                // Run SonarQube analysis
                sh '''
                mvn sonar:sonar \
                    -Dsonar.host.url=http://192.168.33.10:9000 \
                    -Dsonar.login=admin \
                    -Dsonar.password=Rim12356113* \
                    -Dmaven.test.skip=true
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
